code --install-extension 4ops.terraform
code --install-extension adpyke.codesnap
code --install-extension akamud.vscode-theme-onedark
code --install-extension alexcvzz.vscode-sqlite
code --install-extension Artymaury.template-finder
code --install-extension bierner.markdown-emoji
code --install-extension codezombiech.gitignore
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension dongli.python-preview
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension emeraldwalk.RunOnSave
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-diff
code --install-extension foxundermoon.shell-format
code --install-extension golang.go
code --install-extension hangxingliu.vscode-nginx-conf-hint
code --install-extension hashicorp.terraform
code --install-extension imperez.smarty
code --install-extension jmrog.vscode-nuget-package-manager
code --install-extension joaompinto.vscode-graphviz
code --install-extension jongrant.csharpsortusings
code --install-extension k--kato.docomment
code --install-extension lextudio.restructuredtext
code --install-extension magicstack.MagicPython
code --install-extension MariusAlchimavicius.json-to-ts
code --install-extension mikeburgh.xml-format
code --install-extension mikestead.dotenv
code --install-extension mindginative.terraform-snippets
code --install-extension ms-azuretools.vscode-azureterraform
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.powershell
code --install-extension mtxr.sqltools
code --install-extension mtxr.sqltools-driver-sqlite
code --install-extension PascalReitermann93.vscode-yaml-sort
code --install-extension pflannery.vscode-versionlens
code --install-extension PKief.material-icon-theme
code --install-extension quicktype.quicktype
code --install-extension RandomFractalsInc.vscode-data-preview
code --install-extension redhat.vscode-yaml
code --install-extension run-at-scale.terraform-doc-snippets
code --install-extension ryu1kn.partial-diff
code --install-extension samuelcolvin.jinjahtml
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension vscoss.vscode-ansible
code --install-extension WakaTime.vscode-wakatime
code --install-extension whinarn.python-auto-venv
code --install-extension wholroyd.jinja
code --install-extension wwm.better-align
code --install-extension zhuangtongfa.material-theme
